/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ResultScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ScanningProcess`; params?: Router.UnknownInputParams; } | { pathname: `/confirmation_email`; params?: Router.UnknownInputParams; } | { pathname: `/forget-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/select-sector`; params?: Router.UnknownInputParams; } | { pathname: `/setPassword`; params?: Router.UnknownInputParams; } | { pathname: `/startScaningProcess`; params?: Router.UnknownInputParams; } | { pathname: `/verifyEmail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ResultScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ScanningProcess`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmation_email`; params?: Router.UnknownOutputParams; } | { pathname: `/forget-password`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/select-sector`; params?: Router.UnknownOutputParams; } | { pathname: `/setPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/startScaningProcess`; params?: Router.UnknownOutputParams; } | { pathname: `/verifyEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ResultScreen${`?${string}` | `#${string}` | ''}` | `/ScanningProcess${`?${string}` | `#${string}` | ''}` | `/confirmation_email${`?${string}` | `#${string}` | ''}` | `/forget-password${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/select-sector${`?${string}` | `#${string}` | ''}` | `/setPassword${`?${string}` | `#${string}` | ''}` | `/startScaningProcess${`?${string}` | `#${string}` | ''}` | `/verifyEmail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ResultScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ScanningProcess`; params?: Router.UnknownInputParams; } | { pathname: `/confirmation_email`; params?: Router.UnknownInputParams; } | { pathname: `/forget-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/select-sector`; params?: Router.UnknownInputParams; } | { pathname: `/setPassword`; params?: Router.UnknownInputParams; } | { pathname: `/startScaningProcess`; params?: Router.UnknownInputParams; } | { pathname: `/verifyEmail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
